controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
     
    dz_controller:
      type: dz_minimal_controller/DzMinimalController

dz_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces: 
      - position
      - velocity

    state_interfaces:
      - position
      - velocity